/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

/**
 *
 * @author Sakib
 */
public class AreaChoice extends javax.swing.JFrame {

    /**
     * Creates new form AreaChoice
     */
    public AreaChoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectArea = new javax.swing.JLabel();
        dhanmondi = new javax.swing.JButton();
        lalbag = new javax.swing.JButton();
        banani = new javax.swing.JButton();
        mohammadpur = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectArea.setFont(new java.awt.Font("Ravie", 3, 36)); // NOI18N
        selectArea.setForeground(new java.awt.Color(255, 202, 28));
        selectArea.setText("Select an Area");
        getContentPane().add(selectArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 390, -1));

        dhanmondi.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        dhanmondi.setText("Dhanmondi");
        dhanmondi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dhanmondiActionPerformed(evt);
            }
        });
        getContentPane().add(dhanmondi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 223, 61));

        lalbag.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        lalbag.setText("Lalbag");
        getContentPane().add(lalbag, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 223, 61));

        banani.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        banani.setText("Banani");
        banani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bananiActionPerformed(evt);
            }
        });
        getContentPane().add(banani, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 223, 58));

        mohammadpur.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        mohammadpur.setText("Mohammadpur");
        mohammadpur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mohammadpurActionPerformed(evt);
            }
        });
        getContentPane().add(mohammadpur, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, -1, 62));

        logout.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, -1, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/AreaChoice.jpg"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1215, 695));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dhanmondiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dhanmondiActionPerformed
        // TODO add your handling code here:
        new Dhanmondi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dhanmondiActionPerformed

    private void bananiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bananiActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_bananiActionPerformed

    private void mohammadpurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mohammadpurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mohammadpurActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
    new Welcome().setVisible(true);
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaChoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton banani;
    private javax.swing.JButton dhanmondi;
    private javax.swing.JButton lalbag;
    private javax.swing.JButton logout;
    private javax.swing.JButton mohammadpur;
    private javax.swing.JLabel selectArea;
    // End of variables declaration//GEN-END:variables
}
