/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sakib
 */
public class CreateAC extends javax.swing.JFrame {

    /**
     * Creates new form createAC
     */
    public CreateAC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tittle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        mobile = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        passText = new javax.swing.JTextField();
        mobileText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        locationText = new javax.swing.JTextArea();
        createAc = new javax.swing.JButton();
        back = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tittle.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        tittle.setFont(new java.awt.Font("Ravie", 3, 28)); // NOI18N
        tittle.setText("  Please Fill up The Form");
        getContentPane().add(tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 540, 70));

        jLabel2.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        jLabel2.setText("Name                    :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        password.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        password.setText("Password             :");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        mobile.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        mobile.setText("Mobile Number     :");
        getContentPane().add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        location.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        location.setText("Location              :");
        getContentPane().add(location, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));

        nameText.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        getContentPane().add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 500, 50));

        passText.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        getContentPane().add(passText, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 500, 50));

        mobileText.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        getContentPane().add(mobileText, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 500, 50));

        locationText.setColumns(20);
        locationText.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        locationText.setRows(5);
        jScrollPane1.setViewportView(locationText);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 500, -1));

        createAc.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        createAc.setText("Create Account");
        createAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAcActionPerformed(evt);
            }
        });
        getContentPane().add(createAc, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, 240, 70));

        back.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 120, 60));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/CreateAC.jpg"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, -20, -1, -1));

        setSize(new java.awt.Dimension(1215, 695));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAcActionPerformed
    
        // TODO add your handling code here:
        
        String name= nameText.getText();
        String pass= passText.getText();
        String mbl= mobileText.getText();
        String loc= locationText.getText();
        int flag=0;
        int count=0;
    
    {
        try
            (FileWriter fw = new FileWriter("Accounts.txt", true);
            BufferedWriter bw = new BufferedWriter(fw);
             PrintWriter sw = new PrintWriter(bw)) 
        {
            
            
            
            BufferedReader br= null;
        
        
                try {
                    br= new BufferedReader(new FileReader("Accounts.txt"));
                } 
                catch (FileNotFoundException ex) {
                    
                }
                    String line="";
                    while((line=br.readLine())!=null)
                    {
                        String s[]=line.split(" ");
                        
                        if(s[0].equals(name) )
                        {
                            flag=1;
                            JOptionPane.showMessageDialog(null,"Username Already Taken");
                            
                            break;
                        }

                    }
                        if(flag==0)
                        {
                              if("".equals(name)
                                ||"".equals(pass)||
                                "".equals(mbl)||
                                "".equals(loc))
                                    {
                                        count=1;
                                        JOptionPane.showMessageDialog(null," Please, Fill-up the full form first  ");
                          
                                    }
                             else
                              {
                        
                                sw.write(name);
                        
                                sw.write(" ");
                        
                                sw.write(pass);
                                sw.write(" ");
                        
                                sw.write(mbl);
                                sw.write(" ");
                        
                                sw.println(loc);
                                sw.close();
                                
                            }
                try {
                    bw.close();
                    fw.close();
                } catch (Exception ex) {
                    
                }
                    
                }
                        }
            catch (Exception ex) {
                
            }
                        
                    } 
        if(flag==0&&count==0)
        {
            
        JOptionPane.showMessageDialog(null,"Account successfully created");
        new Welcome().setVisible(true);
        this.dispose();
        
        }
    }//GEN-LAST:event_createAcActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
            new Welcome().setVisible(true);
            this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JButton createAc;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel location;
    private javax.swing.JTextArea locationText;
    private javax.swing.JLabel mobile;
    private javax.swing.JTextField mobileText;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField passText;
    private javax.swing.JLabel password;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables
}
