/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

/**
 *
 * @author Sakib
 */
public class First extends javax.swing.JFrame {

    /**
     * Creates new form First
     */
    public First() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hi = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        ready = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        continueB = new javax.swing.JButton();
        foodStop = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hi.setFont(new java.awt.Font("Ravie", 3, 36)); // NOI18N
        hi.setText("  Hi");
        getContentPane().add(hi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 120, 50));

        welcome.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        welcome.setText("  Welcome to the");
        getContentPane().add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 230, 40));

        ready.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        ready.setText("Are You Ready to Go to Food Heaven ??? ");
        getContentPane().add(ready, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, 40));

        jLabel1.setFont(new java.awt.Font("Ravie", 3, 24)); // NOI18N
        jLabel1.setText("Say Yes and Click to Continue");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 520, 40));

        continueB.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        continueB.setText("Continue");
        continueB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBActionPerformed(evt);
            }
        });
        getContentPane().add(continueB, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 160, 60));

        foodStop.setFont(new java.awt.Font("Ravie", 3, 36)); // NOI18N
        foodStop.setText("  \"Food Stop\"");
        getContentPane().add(foodStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 360, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/First.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-670, -280, -1, -1));

        setSize(new java.awt.Dimension(1215, 695));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void continueBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBActionPerformed
    new Welcome().setVisible(true);
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_continueBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new First().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton continueB;
    private javax.swing.JLabel foodStop;
    private javax.swing.JLabel hi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel ready;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
