/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

/**
 *
 * @author Sakib
 */
public class LastPage extends javax.swing.JFrame {

    /**
     * Creates new form LastPage
     */
    public LastPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L1 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        quotes = new javax.swing.JLabel();
        qName = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L1.setFont(new java.awt.Font("Ravie", 3, 36)); // NOI18N
        L1.setForeground(new java.awt.Color(255, 202, 28));
        L1.setText("Your order has been placed.");
        getContentPane().add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 730, -1));

        L2.setFont(new java.awt.Font("Ravie", 3, 75)); // NOI18N
        L2.setForeground(new java.awt.Color(255, 202, 28));
        L2.setText("Thanks");
        getContentPane().add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 410, -1));

        L3.setFont(new java.awt.Font("Ravie", 3, 36)); // NOI18N
        L3.setForeground(new java.awt.Color(255, 202, 28));
        L3.setText("for supporting us.");
        getContentPane().add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 490, -1));

        home.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 140, 60));

        logout.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, 140, 60));

        quotes.setFont(new java.awt.Font("Ravie", 3, 36)); // NOI18N
        quotes.setForeground(new java.awt.Color(255, 202, 28));
        quotes.setText("\"Never eat more than you can lift.\"");
        getContentPane().add(quotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 930, -1));

        qName.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        qName.setForeground(new java.awt.Color(255, 202, 28));
        qName.setText("-Miss Piggy");
        getContentPane().add(qName, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 370, 160, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/rsz_lastpage.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1215, 695));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
    new AreaChoice().setVisible(true);
    this.dispose();
    // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
    new Welcome().setVisible(true);
    this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LastPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LastPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LastPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LastPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LastPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel background;
    private javax.swing.JButton home;
    private javax.swing.JButton logout;
    private javax.swing.JLabel qName;
    private javax.swing.JLabel quotes;
    // End of variables declaration//GEN-END:variables
}
