package javaproject;

public class Takeout extends javax.swing.JFrame {

    /**
     * Creates new form Takeout
     */
      int i=0,j=0;
    public Takeout() {
        initComponents();
    }
    public Takeout(int i,int j)
    {
        initComponents();
        this.i=i;
        this.j=j;
        BeefOrder.setText(String.valueOf(this.j));
        Readorder.setText(String.valueOf(this.i));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NameBur = new javax.swing.JLabel();
        TakeoutLogo = new javax.swing.JLabel();
        BeefChessePrice = new javax.swing.JLabel();
        BeefChesseMinus = new javax.swing.JButton();
        BeefChessePlus = new javax.swing.JButton();
        BeefMinus = new javax.swing.JButton();
        BeefPlus = new javax.swing.JButton();
        Readorder = new javax.swing.JTextField();
        BeefBacon = new javax.swing.JLabel();
        BeefName = new javax.swing.JLabel();
        BeefPrice = new javax.swing.JLabel();
        BeefOrder = new javax.swing.JTextField();
        Order = new javax.swing.JButton();
        back = new javax.swing.JButton();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/bug.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 230, 140));

        NameBur.setBackground(new java.awt.Color(255, 255, 255));
        NameBur.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        NameBur.setText("  Beef Chesse Delight Burger");
        getContentPane().add(NameBur, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 370, 50));

        TakeoutLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/rsz_1takeout_logo.jpg"))); // NOI18N
        getContentPane().add(TakeoutLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 440, 180));

        BeefChessePrice.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        BeefChessePrice.setText("Price: 280 TK");
        getContentPane().add(BeefChessePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, -1, -1));

        BeefChesseMinus.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        BeefChesseMinus.setText("-");
        BeefChesseMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeefChesseMinusActionPerformed(evt);
            }
        });
        getContentPane().add(BeefChesseMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, -1, 30));

        BeefChessePlus.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        BeefChessePlus.setText("+");
        BeefChessePlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeefChessePlusActionPerformed(evt);
            }
        });
        getContentPane().add(BeefChessePlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, -1, 30));

        BeefMinus.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        BeefMinus.setText("-");
        BeefMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeefMinusActionPerformed(evt);
            }
        });
        getContentPane().add(BeefMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, -1, 30));

        BeefPlus.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        BeefPlus.setText("+");
        BeefPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeefPlusActionPerformed(evt);
            }
        });
        getContentPane().add(BeefPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 500, -1, 30));

        Readorder.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        Readorder.setText("  0");
        Readorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadorderActionPerformed(evt);
            }
        });
        getContentPane().add(Readorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 60, 30));

        BeefBacon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/rsz_beef.jpg"))); // NOI18N
        getContentPane().add(BeefBacon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 230, 140));

        BeefName.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        BeefName.setText("Beef & Bacon");
        getContentPane().add(BeefName, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 180, 40));

        BeefPrice.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        BeefPrice.setText("Price: 350 TK");
        getContentPane().add(BeefPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, -1, -1));

        BeefOrder.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        BeefOrder.setText("  0");
        BeefOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeefOrderActionPerformed(evt);
            }
        });
        getContentPane().add(BeefOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, 60, 30));

        Order.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        Order.setText("Order");
        Order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderActionPerformed(evt);
            }
        });
        getContentPane().add(Order, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, 120, 60));

        back.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 130, 60));

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/L0028.jpg"))); // NOI18N
        BackGround.setText("jLabel2");
        getContentPane().add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1460, 850));

        setSize(new java.awt.Dimension(1215, 695));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BeefChessePlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeefChessePlusActionPerformed
        // TODO add your handling code here:
      
        
        i++;
        Readorder.setText(String.valueOf(i));
      
    }//GEN-LAST:event_BeefChessePlusActionPerformed

    private void ReadorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadorderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReadorderActionPerformed

    private void BeefChesseMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeefChesseMinusActionPerformed

       i--;
       Readorder.setText(String.valueOf(i));
    }//GEN-LAST:event_BeefChesseMinusActionPerformed
   
    private void OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderActionPerformed
        // TODO add your handling code here:
        new Order(i,j).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_OrderActionPerformed

    private void BeefPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeefPlusActionPerformed
        // TODO add your handling code here:
         j++;
       BeefOrder.setText(String.valueOf(j));
    }//GEN-LAST:event_BeefPlusActionPerformed

    private void BeefOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeefOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BeefOrderActionPerformed

    private void BeefMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeefMinusActionPerformed
        // TODO add your handling code here:
        if(j>0)
       {
           j--;
       }
       BeefOrder.setText(String.valueOf(j));
    }//GEN-LAST:event_BeefMinusActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    new Dhanmondi().setVisible(true);
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Takeout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Takeout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Takeout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Takeout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Takeout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel BeefBacon;
    private javax.swing.JButton BeefChesseMinus;
    private javax.swing.JButton BeefChessePlus;
    private javax.swing.JLabel BeefChessePrice;
    private javax.swing.JButton BeefMinus;
    private javax.swing.JLabel BeefName;
    private javax.swing.JTextField BeefOrder;
    private javax.swing.JButton BeefPlus;
    private javax.swing.JLabel BeefPrice;
    private javax.swing.JLabel NameBur;
    private javax.swing.JButton Order;
    private javax.swing.JTextField Readorder;
    private javax.swing.JLabel TakeoutLogo;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
