/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sakib
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signIn = new javax.swing.JButton();
        userName = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        createAccount = new javax.swing.JButton();
        passText = new javax.swing.JPasswordField();
        loginText = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signIn.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        signIn.setText("Login");
        signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInActionPerformed(evt);
            }
        });
        getContentPane().add(signIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 110, 50));

        userName.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        userName.setText("Name          :");
        getContentPane().add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 200, -1));

        password.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        password.setText("Password  : ");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 270, -1));

        nameText.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        getContentPane().add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 510, 40));

        createAccount.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        createAccount.setText("Create an account");
        createAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountActionPerformed(evt);
            }
        });
        getContentPane().add(createAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, 270, 50));

        passText.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        getContentPane().add(passText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 510, 40));

        loginText.setFont(new java.awt.Font("Ravie", 3, 36)); // NOI18N
        loginText.setText("Login First To Continue");
        getContentPane().add(loginText, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        back.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, 60));

        background.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/Welcome.jpg"))); // NOI18N
        background.setText("jLabel2");
        background.setAutoscrolls(true);
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 660));

        setSize(new java.awt.Dimension(1215, 695));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInActionPerformed
        // TODO add your handling code here:
         BufferedReader br= null;
        
        try {
            br= new BufferedReader(new FileReader("Accounts.txt"));
            String line="";
            try {
                int flag=0;

                while((line=br.readLine())!=null)
                {
                 String s[]=line.split(" ");
                 String s1=nameText.getText();
                 String s2=passText.getText();

                    if(s[0].equals(s1) && s[1].equals(s2) )
                    {
                        flag=1;
                        new AreaChoice().setVisible(true);
                        this.dispose();
                        break;
                    }

                }
                if(flag==0)
                    {
                        JOptionPane.showMessageDialog(null,"Username Or Password Invalid");
                    }
                // TODO add your handling code here:
            } catch (Exception ex) {
               
            }
        } catch (Exception ex) {
            
        }        
            
    }//GEN-LAST:event_signInActionPerformed

    private void createAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountActionPerformed

        new CreateAC().setVisible(true);                
        this.dispose();
    }//GEN-LAST:event_createAccountActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    new First().setVisible(true);
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JButton createAccount;
    private javax.swing.JLabel loginText;
    private javax.swing.JTextField nameText;
    private javax.swing.JPasswordField passText;
    private javax.swing.JLabel password;
    private javax.swing.JButton signIn;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
